package applications

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/listvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64default"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// applicationResourceSchema returns the full schema for the asgardeo_application resource.
func applicationResourceSchema() schema.Schema {
	return schema.Schema{
		MarkdownDescription: "Manages an application in Asgardeo.\n\n" +
			"Applications can be configured with OIDC or SAML inbound protocol settings. " +
			"The `client_id` and `client_secret` attributes are computed by Asgardeo upon creation " +
			"and should be used to configure your service's identity provider settings.",

		Attributes: map[string]schema.Attribute{
			// ── Computed identity ────────────────────────────────────────────
			"id": schema.StringAttribute{
				MarkdownDescription: "Unique identifier of the application assigned by Asgardeo.",
				Computed:            true,
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"client_id": schema.StringAttribute{
				MarkdownDescription: "OAuth2 / OIDC client ID generated by Asgardeo. Available after creation.",
				Computed:            true,
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"client_secret": schema.StringAttribute{
				MarkdownDescription: "OAuth2 / OIDC client secret generated by Asgardeo. Sensitive.",
				Computed:            true,
				Sensitive:           true,
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},

			// ── Required ──────────────────────────────────────────────────────
			"name": schema.StringAttribute{
				MarkdownDescription: "Display name of the application. Must be unique within the organisation.",
				Required:            true,
			},

			// ── Optional base fields ──────────────────────────────────────────
			"description": schema.StringAttribute{
				MarkdownDescription: "Human-readable description of the application.",
				Optional:            true,
				Computed:            true,
				Default:             stringdefault.StaticString(""),
			},
			"template_id": schema.StringAttribute{
				MarkdownDescription: "Asgardeo application template to seed defaults from. " +
					"Common values: `single-page-application`, `m2m-application`, " +
					"`web-app-template`, `mobile-application`, `custom-application`. " +
					"Required for SPA-style apps — Asgardeo's API rejects (HTTP 500 " +
					"`APP-65006`) public-client + PKCE-mandatory configs without it. " +
					"When omitted Asgardeo applies its default (Standard-Based Web App). " +
					"Templates are create-time-only — changing this value forces resource " +
					"replacement.",
				Optional:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplaceIfConfigured()},
			},
			"access_url": schema.StringAttribute{
				MarkdownDescription: "URL users land on when they launch this application from the My Account portal.",
				Optional:            true,
				Computed:            true,
				Default:             stringdefault.StaticString(""),
			},
			"logout_return_url": schema.StringAttribute{
				MarkdownDescription: "URL users are redirected to after a global logout.",
				Optional:            true,
				Computed:            true,
				Default:             stringdefault.StaticString(""),
			},
			"application_enabled": schema.BoolAttribute{
				MarkdownDescription: "Whether the application is enabled. Defaults to `true`.",
				Optional:            true,
				Computed:            true,
				Default:             booldefault.StaticBool(true),
			},
		},

		Blocks: map[string]schema.Block{
			// ── OIDC ─────────────────────────────────────────────────────────
			"oidc": schema.ListNestedBlock{
				MarkdownDescription: "OIDC / OAuth2 inbound protocol configuration. " +
					"Specify exactly one of `oidc` or `saml`.",
				Validators: []validator.List{listvalidator.SizeAtMost(1)},
				NestedObject: schema.NestedBlockObject{
					Attributes: map[string]schema.Attribute{
						"grant_types": schema.ListAttribute{
							MarkdownDescription: "OAuth2 grant types to enable. At least one is required.\n\n" +
								"Supported values: `authorization_code`, `client_credentials`, `refresh_token`, " +
								"`implicit`, `password`, `token_exchange`, `organization_switch`.",
							Required:    true,
							ElementType: types.StringType,
						},
						"callback_urls": schema.ListAttribute{
							MarkdownDescription: "Allowed redirect (callback) URIs. " +
								"Required when `authorization_code` or `implicit` grant types are used.\n\n" +
								"Tip: this is the field Rancher calls **Authorized Redirect URIs**.",
							Optional:    true,
							Computed:    true,
							ElementType: types.StringType,
						},
						"allowed_origins": schema.ListAttribute{
							MarkdownDescription: "CORS-allowed origins for token and authorisation requests. " +
								"Relevant for browser-based (SPA) applications and Rancher OIDC.",
							Optional:    true,
							Computed:    true,
							ElementType: types.StringType,
						},
						"logout_redirect_urls": schema.ListAttribute{
							MarkdownDescription: "Post-logout redirect URIs. " +
								"Stored as the OIDC front-channel logout URL in Asgardeo. " +
								"Tip: this is the URL Rancher uses after a user signs out.",
							Optional:    true,
							Computed:    true,
							ElementType: types.StringType,
						},
						"public_client": schema.BoolAttribute{
							MarkdownDescription: "When `true` the client may authenticate without a secret (e.g. SPAs). " +
								"Defaults to `false`.",
							Optional: true,
							Computed: true,
							Default:  booldefault.StaticBool(false),
						},
					},
					Blocks: map[string]schema.Block{
						"pkce": schema.ListNestedBlock{
							MarkdownDescription: "PKCE (Proof Key for Code Exchange) settings.",
							Validators:          []validator.List{listvalidator.SizeAtMost(1)},
							NestedObject: schema.NestedBlockObject{
								Attributes: map[string]schema.Attribute{
									"mandatory": schema.BoolAttribute{
										MarkdownDescription: "Require PKCE for all authorisation code flows. Defaults to `false`.",
										Optional:            true,
										Computed:            true,
										Default:             booldefault.StaticBool(false),
									},
									"support_plain_transform_algorithm": schema.BoolAttribute{
										MarkdownDescription: "Allow the plain (S256-less) code challenge method. Defaults to `false`.",
										Optional:            true,
										Computed:            true,
										Default:             booldefault.StaticBool(false),
									},
								},
							},
						},
						"access_token": schema.ListNestedBlock{
							MarkdownDescription: "Access token configuration.",
							Validators:          []validator.List{listvalidator.SizeAtMost(1)},
							NestedObject: schema.NestedBlockObject{
								Attributes: map[string]schema.Attribute{
									"type": schema.StringAttribute{
										MarkdownDescription: "Token type: `JWT` or `Default` (opaque). Defaults to `JWT`.",
										Optional:            true,
										Computed:            true,
										Default:             stringdefault.StaticString("JWT"),
										Validators: []validator.String{
											stringvalidator.OneOf("JWT", "Default"),
										},
									},
									"user_access_token_expiry_seconds": schema.Int64Attribute{
										MarkdownDescription: "User access token TTL in seconds. Defaults to 3600.",
										Optional:            true,
										Computed:            true,
										Default:             int64default.StaticInt64(3600),
									},
									"application_access_token_expiry_seconds": schema.Int64Attribute{
										MarkdownDescription: "Application (M2M) access token TTL in seconds. Defaults to 3600.",
										Optional:            true,
										Computed:            true,
										Default:             int64default.StaticInt64(3600),
									},
								},
							},
						},
						"refresh_token": schema.ListNestedBlock{
							MarkdownDescription: "Refresh token configuration.",
							Validators:          []validator.List{listvalidator.SizeAtMost(1)},
							NestedObject: schema.NestedBlockObject{
								Attributes: map[string]schema.Attribute{
									"expiry_seconds": schema.Int64Attribute{
										MarkdownDescription: "Refresh token TTL in seconds. Defaults to 86400 (24 h).",
										Optional:            true,
										Computed:            true,
										Default:             int64default.StaticInt64(86400),
									},
									"renew_refresh_token": schema.BoolAttribute{
										MarkdownDescription: "Issue a new refresh token on each use. Defaults to `true`.",
										Optional:            true,
										Computed:            true,
										Default:             booldefault.StaticBool(true),
									},
								},
							},
						},
					},
				},
			},

			// ── SAML ─────────────────────────────────────────────────────────
			"saml": schema.ListNestedBlock{
				MarkdownDescription: "SAML 2.0 inbound protocol configuration. " +
					"Specify exactly one of `oidc` or `saml`.",
				Validators: []validator.List{listvalidator.SizeAtMost(1)},
				NestedObject: schema.NestedBlockObject{
					Blocks: map[string]schema.Block{
						"manual_configuration": schema.ListNestedBlock{
							MarkdownDescription: "Manually specify SAML metadata fields.",
							Validators:          []validator.List{listvalidator.SizeAtMost(1)},
							NestedObject: schema.NestedBlockObject{
								Attributes: map[string]schema.Attribute{
									"issuer": schema.StringAttribute{
										MarkdownDescription: "SAML SP entity ID (issuer).",
										Required:            true,
									},
									"assertion_consumer_urls": schema.ListAttribute{
										MarkdownDescription: "List of assertion consumer service (ACS) URLs.",
										Required:            true,
										ElementType:         types.StringType,
									},
									"default_assertion_consumer_url": schema.StringAttribute{
										MarkdownDescription: "Default ACS URL. Must be one of `assertion_consumer_urls`.",
										Optional:            true,
										Computed:            true,
										Default:             stringdefault.StaticString(""),
									},
								},
								Blocks: map[string]schema.Block{
									"single_logout": schema.ListNestedBlock{
										MarkdownDescription: "Single logout profile settings.",
										Validators:          []validator.List{listvalidator.SizeAtMost(1)},
										NestedObject: schema.NestedBlockObject{
											Attributes: map[string]schema.Attribute{
												"enabled": schema.BoolAttribute{
													MarkdownDescription: "Enable single logout. Defaults to `true`.",
													Optional:            true,
													Computed:            true,
													Default:             booldefault.StaticBool(true),
												},
												"logout_request_url": schema.StringAttribute{
													Optional: true,
													Computed: true,
													Default:  stringdefault.StaticString(""),
												},
												"logout_response_url": schema.StringAttribute{
													Optional: true,
													Computed: true,
													Default:  stringdefault.StaticString(""),
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},

			// ── Claim Configuration ───────────────────────────────────────────
			"claim_configuration": schema.ListNestedBlock{
				MarkdownDescription: "Controls which user attributes (claims) are included in tokens issued to this application. " +
					"Use this to ensure claims like `email` or `username` are returned in the OIDC token so that " +
					"Rancher (and other relying parties) can display readable usernames.",
				Validators: []validator.List{listvalidator.SizeAtMost(1)},
				NestedObject: schema.NestedBlockObject{
					Blocks: map[string]schema.Block{
						"requested_claims": schema.ListNestedBlock{
							MarkdownDescription: "List of local claims to include in the token. " +
								"Common Asgardeo claim URIs:\n\n" +
								"- `http://wso2.org/claims/emailaddress` — email address\n" +
								"- `http://wso2.org/claims/username` — username\n" +
								"- `http://wso2.org/claims/givenname` — first name\n" +
								"- `http://wso2.org/claims/lastname` — last name",
							NestedObject: schema.NestedBlockObject{
								Attributes: map[string]schema.Attribute{
									"uri": schema.StringAttribute{
										MarkdownDescription: "Local claim URI, e.g. `http://wso2.org/claims/emailaddress`.",
										Required:            true,
									},
									"mandatory": schema.BoolAttribute{
										MarkdownDescription: "Require the claim to be present. Defaults to `false`.",
										Optional:            true,
										Computed:            true,
										Default:             booldefault.StaticBool(false),
									},
								},
							},
						},
					},
				},
			},

			// ── Advanced ──────────────────────────────────────────────────────
			"advanced": schema.ListNestedBlock{
				MarkdownDescription: "Advanced application configuration.",
				Validators:          []validator.List{listvalidator.SizeAtMost(1)},
				NestedObject: schema.NestedBlockObject{
					Attributes: map[string]schema.Attribute{
						"skip_login_consent": schema.BoolAttribute{
							MarkdownDescription: "Skip the user consent screen on login. Defaults to `false`.",
							Optional:            true,
							Computed:            true,
							Default:             booldefault.StaticBool(false),
						},
						"skip_logout_consent": schema.BoolAttribute{
							MarkdownDescription: "Skip the user consent screen on logout. Defaults to `false`.",
							Optional:            true,
							Computed:            true,
							Default:             booldefault.StaticBool(false),
						},
						"saas": schema.BoolAttribute{
							MarkdownDescription: "Mark this as a SaaS (multi-tenant) application. Defaults to `false`.",
							Optional:            true,
							Computed:            true,
							Default:             booldefault.StaticBool(false),
						},
						"discoverable_by_end_users": schema.BoolAttribute{
							MarkdownDescription: "Show this application in the My Account portal. Defaults to `false`.",
							Optional:            true,
							Computed:            true,
							Default:             booldefault.StaticBool(false),
						},
					},
				},
			},
		},
	}
}
